source activate /data01nfs/user/liupf/miniconda3/envs/trimmomatic/
trimmomatic PE -threads 20  /data02nfs/Project/chihf/QY_metatrans/QYJanS1-1.R1.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS1-1.R2.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS1_R1_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS1_R1_trimmed_U.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS1_R2_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS1_R2_trimmed_U.fq.gz ILLUMINACLIP:/data01nfs/user/liupf/common_files/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
trimmomatic PE -threads 20  /data02nfs/Project/chihf/QY_metatrans/QYJanS7-1.R1.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS7-1.R2.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS7_R1_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS7_R1_trimmed_U.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS7_R2_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS7_R2_trimmed_U.fq.gz ILLUMINACLIP:/data01nfs/user/liupf/common_files/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
trimmomatic PE -threads 20  /data02nfs/Project/chihf/QY_metatrans/QYJanS9-1.R1.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS9-1.R2.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS9_R1_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS9_R1_trimmed_U.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS9_R2_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYJanS9_R2_trimmed_U.fq.gz ILLUMINACLIP:/data01nfs/user/liupf/common_files/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
trimmomatic PE -threads 20  /data02nfs/Project/chihf/QY_metatrans/QYMayS1-1.R1.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS1-1.R2.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS1_R1_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS1_R1_trimmed_U.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS1_R2_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS1_R2_trimmed_U.fq.gz ILLUMINACLIP:/data01nfs/user/liupf/common_files/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
trimmomatic PE -threads 20  /data02nfs/Project/chihf/QY_metatrans/QYMayS7-1.R1.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS7-1.R2.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS7_R1_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS7_R1_trimmed_U.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS7_R2_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS7_R2_trimmed_U.fq.gz ILLUMINACLIP:/data01nfs/user/liupf/common_files/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 
trimmomatic PE -threads 20  /data02nfs/Project/chihf/QY_metatrans/QYMayS9-1.R1.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS9-1.R2.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS9_R1_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS9_R1_trimmed_U.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS9_R2_trimmed.fq.gz  /data02nfs/Project/chihf/QY_metatrans/QYMayS9_R2_trimmed_U.fq.gz ILLUMINACLIP:/data01nfs/user/liupf/common_files/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 




